create table heroes (id int8 generated by default as identity, name varchar(255), hero_type varchar(255), profile_picture oid, primary key (id));
INSERT INTO heroes(name, hero_type) VALUES('Superman', 'DC');
INSERT INTO heroes(name, hero_type) VALUES('Batman', 'DC');
INSERT INTO heroes(name, hero_type) VALUES('Thor', 'MARVEL');
INSERT INTO heroes(name, hero_type) VALUES('Capitão América', 'MARVEL');
