create table heroes (id int8 generated by default as identity, hero_type varchar(255), name varchar(255), profile_picture bytea, primary key (id));
INSERT INTO heroes(name, hero_type, profile_picture) VALUES('Superman', 'DC', null);
INSERT INTO heroes(name, hero_type, profile_picture) VALUES('Batman', 'DC',  null);
INSERT INTO heroes(name, hero_type, profile_picture) VALUES('Thor', 'MARVEL', null);
INSERT INTO heroes(name, hero_type, profile_picture) VALUES('Capitão América', 'MARVEL', null);
